<#
.SYNOPSIS
  One-stop, reproducible bootstrap (and optional deployment) for this solution.

.DESCRIPTION
  Prompts for the handful of environment-specific values this solution needs, writes them to a
  single git-ignored `.env` at the repo root (the source of truth every other script reads via
  scripts/lib/DotEnv.ps1), and pushes them to GitHub Actions as repository variables with
  `gh variable set`.

  With -Deploy, it also runs the full deployment locally:
    1. Provisions Azure resources with Bicep (infra/main.bicep).
    2. Captures the deployment outputs (APIM name, Function App name, Dev Portal URL) back into
       `.env` and as the `AZURE_FUNCTIONAPP_NAME` repo variable.
    3. Builds and zip-deploys the Function App.
    4. Raises product subscription limits and deploys the Dev Portal custom widgets.

  Resource names are `<prefix>-<type>-<uniqueString(resourceGroup)>`; the trailing suffix is
  generated by Azure at deploy time and cannot be known beforehand, which is why the
  APIM/Function names and URLs are only filled in after a deploy.

.PARAMETER Deploy
  After writing `.env` and setting GitHub variables, run the actual Azure deployment.

.PARAMETER SkipGitHub
  Do not call `gh variable set` (only write `.env`). Useful when you don't have the gh CLI or
  aren't managing the repo variables from this machine.

.PARAMETER NonInteractive
  Do not prompt; use existing `.env` values / parameters as-is. Fails if a required value is missing.

.PARAMETER EnvFile
  Path to the .env file to read/write. Defaults to `.env` at the repo root.

.EXAMPLE
  ./scripts/Deploy.ps1
  # Interactive bootstrap: prompts, writes .env, sets GitHub variables.

.EXAMPLE
  ./scripts/Deploy.ps1 -Deploy
  # Bootstrap + provision infra + deploy app + widgets, capturing outputs into .env.

.EXAMPLE
  ./scripts/Deploy.ps1 -NonInteractive -Deploy
  # Re-deploy using the values already in .env (CI-style, no prompts).
#>
[CmdletBinding()]
param(
  [switch]$Deploy,
  [switch]$SkipGitHub,
  [switch]$NonInteractive,
  [string]$EnvFile
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot "lib/DotEnv.ps1")

if (-not $EnvFile) { $EnvFile = Join-Path $repoRoot ".env" }

# Existing values (from .env) become the defaults offered at each prompt.
$existing = Import-DotEnv -Path $EnvFile -SetEnv $false

function Read-Value {
  param(
    [Parameter(Mandatory)][string]$Key,
    [string]$Prompt,
    [string]$Default,
    [switch]$Required
  )
  $current = if ($existing.Contains($Key) -and $existing[$Key]) { $existing[$Key] } else { $Default }

  if ($NonInteractive) {
    if ($Required -and [string]::IsNullOrWhiteSpace($current)) {
      throw "Missing required value '$Key' and running -NonInteractive."
    }
    return $current
  }

  $label = if ($Prompt) { $Prompt } else { $Key }
  $suffix = if ($current) { " [$current]" } else { "" }
  $answer = Read-Host "$label$suffix"
  if ([string]::IsNullOrWhiteSpace($answer)) { $answer = $current }
  if ($Required -and [string]::IsNullOrWhiteSpace($answer)) {
    throw "'$Key' is required."
  }
  return $answer
}

Write-Host "=== Configure deployment ===" -ForegroundColor Cyan
Write-Host "Press Enter to keep the value shown in [brackets]." -ForegroundColor DarkGray

$prefix = Read-Value -Key "RESOURCE_PREFIX" -Prompt "Resource name prefix (3-11 lowercase alphanumeric)" -Required
if ($prefix -notmatch '^[a-z0-9]{3,11}$') {
  throw "RESOURCE_PREFIX '$prefix' must be 3-11 lowercase alphanumeric characters."
}

$location   = Read-Value -Key "AZURE_LOCATION" -Prompt "Azure region" -Default "northeurope" -Required
$rgDefault  = if ($existing.Contains("AZURE_RESOURCE_GROUP") -and $existing["AZURE_RESOURCE_GROUP"]) { $existing["AZURE_RESOURCE_GROUP"] } else { "rg-$prefix-dev" }
$resourceGroup = Read-Value -Key "AZURE_RESOURCE_GROUP" -Prompt "Resource group name" -Default $rgDefault -Required

$subscriptionId = Read-Value -Key "AZURE_SUBSCRIPTION_ID" -Prompt "Azure subscription id" -Required
$tenantId       = Read-Value -Key "AZURE_TENANT_ID" -Prompt "Entra tenant id" -Required
$clientId       = Read-Value -Key "AZURE_CLIENT_ID" -Prompt "OIDC app/UAMI client id" -Required

$publisherEmail = Read-Value -Key "APIM_PUBLISHER_EMAIL" -Prompt "APIM publisher email" -Required
$publisherName  = Read-Value -Key "APIM_PUBLISHER_NAME" -Prompt "APIM publisher (organization) name" -Default "Group Subscriptions" -Required

$testUser = Read-Value -Key "DEVPORTAL_TEST_USERNAME" -Prompt "Dev Portal E2E test username" -Default "testuser@test.com"
$testPass = Read-Value -Key "DEVPORTAL_TEST_PASSWROD" -Prompt "Dev Portal E2E test password" -Default ""

# Preserve any output values already captured from a previous deploy.
$apimServiceName = if ($existing.Contains("APIM_SERVICE_NAME")) { $existing["APIM_SERVICE_NAME"] } else { "" }
$functionAppName = if ($existing.Contains("AZURE_FUNCTIONAPP_NAME")) { $existing["AZURE_FUNCTIONAPP_NAME"] } else { "" }
$functionBaseUrl = if ($existing.Contains("FUNCTION_BASE_URL")) { $existing["FUNCTION_BASE_URL"] } else { "" }
$devPortalUrl    = if ($existing.Contains("DEVPORTAL_URL")) { $existing["DEVPORTAL_URL"] } else { "" }

$envValues = [ordered]@{
  AZURE_CLIENT_ID         = $clientId
  AZURE_TENANT_ID         = $tenantId
  AZURE_SUBSCRIPTION_ID   = $subscriptionId
  AZURE_RESOURCE_GROUP    = $resourceGroup
  AZURE_LOCATION          = $location
  RESOURCE_PREFIX         = $prefix
  APIM_PUBLISHER_EMAIL    = $publisherEmail
  APIM_PUBLISHER_NAME     = $publisherName
  APIM_SERVICE_NAME       = $apimServiceName
  AZURE_FUNCTIONAPP_NAME  = $functionAppName
  FUNCTION_BASE_URL       = $functionBaseUrl
  DEVPORTAL_URL           = $devPortalUrl
  DEVPORTAL_TEST_USERNAME = $testUser
  DEVPORTAL_TEST_PASSWROD = $testPass
}

# Seed a brand-new .env from the sample so comments/structure are preserved.
if (-not (Test-Path -LiteralPath $EnvFile)) {
  $sample = Join-Path $repoRoot ".env.sample"
  if (Test-Path -LiteralPath $sample) { Copy-Item -LiteralPath $sample -Destination $EnvFile }
}
Set-DotEnvValues -Path $EnvFile -Values $envValues
Write-Host "Wrote $EnvFile" -ForegroundColor Green

# --- GitHub Actions repository variables ---------------------------------------------------------
function Set-GhVariables {
  param([System.Collections.IDictionary]$Values)

  if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Warning "gh CLI not found; skipping GitHub variable setup. Set these repository variables manually:"
    foreach ($k in $Values.Keys) { Write-Host "  $k = $($Values[$k])" }
    return
  }
  # These are the variables the workflows require (secrets/outputs excluded).
  $keys = @(
    "AZURE_CLIENT_ID", "AZURE_TENANT_ID", "AZURE_SUBSCRIPTION_ID",
    "AZURE_RESOURCE_GROUP", "AZURE_LOCATION", "RESOURCE_PREFIX",
    "APIM_PUBLISHER_EMAIL", "APIM_PUBLISHER_NAME"
  )
  if ($Values["AZURE_FUNCTIONAPP_NAME"]) { $keys += "AZURE_FUNCTIONAPP_NAME" }

  foreach ($k in $keys) {
    $val = $Values[$k]
    if ([string]::IsNullOrWhiteSpace($val)) { continue }
    Write-Host "  gh variable set $k" -ForegroundColor DarkGray
    $val | gh variable set $k --body -  2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
      Write-Warning "Failed to set '$k' via gh. Ensure 'gh auth login' has run and you have repo admin."
    }
  }
}

if ($SkipGitHub) {
  Write-Host "SkipGitHub set - not touching GitHub Actions variables." -ForegroundColor Yellow
} else {
  Write-Host "`n=== Setting GitHub Actions repository variables ===" -ForegroundColor Cyan
  Set-GhVariables -Values $envValues
}

if (-not $Deploy) {
  Write-Host "`nBootstrap complete. Re-run with -Deploy to provision Azure and deploy the app + widgets." -ForegroundColor Green
  return
}

# --- Full deployment -----------------------------------------------------------------------------
Write-Host "`n=== Deploying ===" -ForegroundColor Cyan
if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
  throw "Azure CLI (az) is required for -Deploy. Install it and run 'az login'."
}

az account set --subscription $subscriptionId | Out-Null

Write-Host "Ensuring resource group '$resourceGroup' in '$location'..." -ForegroundColor Cyan
az group create --name $resourceGroup --location $location -o none

Write-Host "Deploying infrastructure (Bicep)... this can take 30-45 min on first APIM provision." -ForegroundColor Cyan
$paramsFile = Join-Path $repoRoot "infra/main.parameters.dev.json"
$deployName = "deploy-$(Get-Date -Format yyyyMMddHHmmss)"
$outputsJson = az deployment group create `
  --name $deployName `
  --resource-group $resourceGroup `
  --template-file (Join-Path $repoRoot "infra/main.bicep") `
  --parameters $paramsFile `
  --parameters prefix=$prefix location=$location publisherEmail=$publisherEmail "publisherName=$publisherName" `
  --query properties.outputs -o json
if ($LASTEXITCODE -ne 0) { throw "Infrastructure deployment failed." }

$outputs = $outputsJson | ConvertFrom-Json
$functionAppName = $outputs.functionAppName.value
$apimServiceName = $outputs.apimName.value
$devPortalUrl    = $outputs.developerPortalUrl.value
$functionBaseUrl = "https://$functionAppName.azurewebsites.net/api"

Write-Host "  Function App : $functionAppName" -ForegroundColor Green
Write-Host "  APIM service : $apimServiceName" -ForegroundColor Green
Write-Host "  Dev Portal   : $devPortalUrl" -ForegroundColor Green

# Fold the outputs back into .env and GitHub variables.
$outValues = [ordered]@{
  APIM_SERVICE_NAME      = $apimServiceName
  AZURE_FUNCTIONAPP_NAME = $functionAppName
  FUNCTION_BASE_URL      = $functionBaseUrl
  DEVPORTAL_URL          = $devPortalUrl
}
Set-DotEnvValues -Path $EnvFile -Values $outValues
foreach ($k in $outValues.Keys) { $envValues[$k] = $outValues[$k] }
if (-not $SkipGitHub) { Set-GhVariables -Values $envValues }

# Build + zip-deploy the Function App.
Write-Host "`nBuilding and deploying the Function App..." -ForegroundColor Cyan
$projectPath = Join-Path $repoRoot "src/GroupSubscriptions.Functions"
$publishDir  = Join-Path $repoRoot "publish"
$zipPath     = Join-Path $repoRoot "app.zip"
dotnet publish $projectPath --configuration Release --output $publishDir
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed." }
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $publishDir "*") -DestinationPath $zipPath -Force
az functionapp deployment source config-zip -g $resourceGroup -n $functionAppName --src $zipPath -o none
if ($LASTEXITCODE -ne 0) { throw "Function App zip deploy failed." }

# Raise product subscription limits so standalone group subscriptions aren't blocked.
Write-Host "`nRaising product subscription limits..." -ForegroundColor Cyan
& (Join-Path $repoRoot "infra/scripts/Set-ProductSubscriptionLimits.ps1") -ResourceGroup $resourceGroup -ApimName $apimServiceName -Limit 10000

# Deploy the Dev Portal custom widgets (reads the .env we just wrote).
Write-Host "`nDeploying custom widgets..." -ForegroundColor Cyan
& (Join-Path $repoRoot "src/widgets/scripts/deploy-widgets.ps1")

Write-Host "`nDeployment complete." -ForegroundColor Green
